### ISSUE TITLE
Could not open file Error

### ISSUE THREAD

**Issue by bapoorva** [wanglab-upenn/HAMR#1]
Hi,

I was trying to run HAMR on one of my bam files. I tried using the GUI. Each time Im getting this error

GUI
Error: filtering pileup...;Could not open file /data/tmp2/7774cf5e1f6635234d962ac48f744bbe;

I even tried it with the trial.human.bam file. Still doesnt work for me. Can you please let me know what might be the problem?

Thanks
apoorva

**Comment by pkuksa** [comment]
Hi,

What was the command used to run HAMR? 

This should finish with no errors if you run it from HAMR directory (make sure the genome fasta file hg19.fa is there!): 
python hamr.py trial.human.bam hg19.fa models/euk_trna_mods.Rdata HAMRtrial trial 0.05 50 0.05 H4  0.01 0.05 0.05

Also, the provided run_hamr.sh should run with no issues!
bash run_hamr.sh

Thanks!

Best,

Pavel

**Comment by bapoorva** [comment]
No I used the GUI. I went to this link http://tesla.pcbi.upenn.edu/hamr/# and uploaded my BAM file. It started running but gave this error 
```ruby
Error: filtering pileup...;Could not open file /data/tmp2/7774cf5e1f6635234d962ac48f744bbe;
```
I compiled it and ran it using the command line as well. I tried both genome-wide and target modes using the following commands
```ruby
python2.7 ./hamr.py ~/projects/GATK/adult_splitN_uniq_sorted.bam ~/NGS/mm9/mm9_all_chr.fas ~/HAMR-1.2/models/euk_trna_mods.Rdata ~/projects/HAMR mm9_adE16.5 30 10 0.05 H4 0.01 0.05 0.05
```
```ruby
python2.7 ./hamr.py ~/projects/GATK/adult_splitN_uniq_sorted.bam ~/NGS/mm9/mm9_all_chr.fas ~/HAMR-1.2/models/euk_trna_mods.Rdata ~/projects/HAMR mm9_adE16.5 --target_bed ~/NGSshare/mm9_data/test.bed 30 10 0.05 H4 0.01 0.05 0.05
```
Now I'm getting this error
```ruby
*** glibc detected *** /home/bapoorva/HAMR-1.2/filter_pileup: double free or corruption (out): 0x0000000002199050 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3e61875dee]
/lib64/libc.so.6[0x3e61878c80]
/home/bapoorva/HAMR-1.2/filter_pileup[0x402d81]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3e6181ed1d]
/home/bapoorva/HAMR-1.2/filter_pileup[0x401899]
======= Memory map: ========
00400000-00404000 r-xp 00000000 00:19 276970734                          /home/bapoorva/HAMR-1.2/filter_pileup
00604000-00605000 rw-p 00004000 00:19 276970734                          /home/bapoorva/HAMR-1.2/filter_pileup
02196000-021b7000 rw-p 00000000 00:00 0                                  [heap]
3e61400000-3e61420000 r-xp 00000000 fd:00 2359494                        /lib64/ld-2.12.so
3e61620000-3e61621000 r--p 00020000 fd:00 2359494                        /lib64/ld-2.12.so
3e61621000-3e61622000 rw-p 00021000 fd:00 2359494                        /lib64/ld-2.12.so
3e61622000-3e61623000 rw-p 00000000 00:00 0 
3e61800000-3e6198a000 r-xp 00000000 fd:00 2359576                        /lib64/libc-2.12.so
3e6198a000-3e61b8a000 ---p 0018a000 fd:00 2359576                        /lib64/libc-2.12.so
3e61b8a000-3e61b8e000 r--p 0018a000 fd:00 2359576                        /lib64/libc-2.12.so
3e61b8e000-3e61b90000 rw-p 0018e000 fd:00 2359576                        /lib64/libc-2.12.so
3e61b90000-3e61b94000 rw-p 00000000 00:00 0 
3e61c00000-3e61c83000 r-xp 00000000 fd:00 2359646                        /lib64/libm-2.12.so
3e61c83000-3e61e82000 ---p 00083000 fd:00 2359646                        /lib64/libm-2.12.so
3e61e82000-3e61e83000 r--p 00082000 fd:00 2359646                        /lib64/libm-2.12.so
3e61e83000-3e61e84000 rw-p 00083000 fd:00 2359646                        /lib64/libm-2.12.so
3e62c00000-3e62c15000 r-xp 00000000 fd:00 2359664                        /lib64/libz.so.1.2.3
3e62c15000-3e62e14000 ---p 00015000 fd:00 2359664                        /lib64/libz.so.1.2.3
3e62e14000-3e62e15000 r--p 00014000 fd:00 2359664                        /lib64/libz.so.1.2.3
3e62e15000-3e62e16000 rw-p 00015000 fd:00 2359664                        /lib64/libz.so.1.2.3
3e63400000-3e63416000 r-xp 00000000 fd:00 2359647                        /lib64/libgcc_s-4.4.7-20120601.so.1
3e63416000-3e63615000 ---p 00016000 fd:00 2359647                        /lib64/libgcc_s-4.4.7-20120601.so.1
3e63615000-3e63616000 rw-p 00015000 fd:00 2359647                        /lib64/libgcc_s-4.4.7-20120601.so.1
3e65c00000-3e65ce8000 r-xp 00000000 fd:00 919660                         /usr/lib64/libstdc++.so.6.0.13
3e65ce8000-3e65ee8000 ---p 000e8000 fd:00 919660                         /usr/lib64/libstdc++.so.6.0.13
3e65ee8000-3e65eef000 r--p 000e8000 fd:00 919660                         /usr/lib64/libstdc++.so.6.0.13
3e65eef000-3e65ef1000 rw-p 000ef000 fd:00 919660                         /usr/lib64/libstdc++.so.6.0.13
3e65ef1000-3e65f06000 rw-p 00000000 00:00 0 
7f2d10000000-7f2d10021000 rw-p 00000000 00:00 0 
7f2d10021000-7f2d14000000 ---p 00000000 00:00 0 
7f2d16416000-7f2d1651c000 rw-p 00000000 00:00 0 
7f2d16532000-7f2d16534000 rw-p 00000000 00:00 0 
7fff8af4a000-7fff8b05f000 rw-p 00000000 00:00 0                          [stack]
7fff8b0ca000-7fff8b0cb000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Traceback (most recent call last):
  File "./hamr.py", line 138, in <module>
    subprocess.check_call([filter_pileup,rawpileup,str(args.min_qual),str(int(args.filter_ends))],stdout=ffilteredpileup)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/bapoorva/HAMR-1.2/filter_pileup', '/home/bapoorva/projects/Morrisey/Ian/AT1_AT2_Timecourse/HAMR/HAMR_temp/HAMR.mm9_AT1_AT2.pileup.raw', '30', '0']' returned non-zero exit status -6
```

**Comment by pkuksa** [comment]
Hi,

Can you please run the wrapper script for the sample BAM and hg19:
bash run_hamr.sh
Does it finish without errors?
If it runs correctly, then there may be an issue caused by the GATK bam file itself.

Thanks!

Best,
Pavel

**Comment by bapoorva** [comment]
I did. That runs without any issues. So i fixed a few things and edited the same wrapper script for my data and mm9. Now Im getting this

```ruby
HAMR (BED-restricted):
python2.7 hamr.py /home/bapoorva/projects/GATK/adult_1_splitN_uniq_sorted.bam mm9_all_chr.fas models/euk_trna_mods.Rdata HAMRtrial trial_mouse  0.05 50 0.05 H4  0.01 0.05 0.05 --target_bed region.mouse.bed
Existing output folder HAMRtrial detected, will overwrite all internal files
Analyzing /home/bapoorva/projects/GATK/adult_1_splitN_uniq_sorted.bam (targeted)
Target BED is specified: region.mouse.bed
Restricting BAM to regions in region.mouse.bed
BAM for HAMR analysis: HAMRtrial/adult_1_splitN_uniq_sorted.constrained.bam
Running RNApileup /home/bapoorva/HAMR-1.2/rnapileup
Encountered new ref: chr1; loading... loaded
Running filter_pileup...
Filter coverage...
Running rnapileup2mismatchbed...
converting mismatch BED to nucleotide frequency table
testing for statistical significance...
Error in hyp.ps[i, sprintf("%s%s", x$refnuc[i], x$refnuc[i])] : 
  subscript out of bounds
Calls: sapply -> lapply -> FUN
Execution halted
Traceback (most recent call last):
  File "hamr.py", line 183, in <module>
    subprocess.check_call([RSCRIPT,detect_mods_definite,last_tmp_file,args.seq_err,args.hypothesis,args.max_p,args.max_fdr,args.refpercent],stdout=outfn)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/Rscript', '/home/bapoorva/HAMR-1.2/detect_mods.R', 'HAMRtrial/HAMR_temp/HAMR.trial_mouse.freqtable.final.txt', '0.05', 'H4', '0.01', '0.05', '0.05']' returned non-zero exit status 1


***Failed to run:
python2.7 hamr.py /home/bapoorva/GATK/adult_1_splitN_uniq_sorted.bam mm9_all_chr.fas models/euk_trna_mods.Rdata HAMRtrial trial_mouse  0.05 50 0.05 H4  0.01 0.05 0.05 --target_bed region.mouse.bed

```

**Comment by pkuksa** [comment]
Hi,

Can you check if the input file for detect_mods.R,
'HAMRtrial/HAMR_temp/HAMR.trial_mouse.freqtable.final.txt',
is correctly generated?

It should look something like this:
chr1	1103310	+	A	52	1	0	0	1
chr1	1103315	+	G	1	0	52	0	1
chr1	9211791	-	G	59	1	72	106	166

Thanks!

Best,
Pavel

**Comment by bapoorva** [comment]
Well its only creating an empty HAMR.trial_mouse.freqtable.final.txt file. Nothing in it
